<?php

/**
 * @file
 * Contains cookies_video.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cookies_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cookies_ga module.
    case 'help.page.cookies_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Submodule of COOKiES to manage video media items (by "media" module) inside of COOKiES consent management.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function cookies_video_preprocess_field(&$variables) {
  if ($variables["element"]["#formatter"] == 'oembed') {

    foreach ($variables["items"] as &$item) {
      // Move src to data-src and replace src by fallback.
      $src = $item["content"]["#attributes"]["src"];
      $item["content"]["#attributes"]["data-src"] = $src;
      $item["content"]["#attributes"]["src"] = '';

      // Set marker class.
      if (!isset($item["content"]["#attributes"]["class"]) || !is_array($item["content"]["#attributes"]["class"])) {
        $item["content"]["#attributes"]["class"] = [];
      }
      $item["content"]["#attributes"]["class"][] = 'cookies-video';

      // Attach library.
      if (!isset($item["content"]["#attached"])) {
        $item["content"]["#attached"] = ["library" => []];
      }
      if (!isset($item["content"]["#attached"]["library"])) {
        $item["content"]["#attached"]["library"] = [];
      }
      $item["content"]["#attached"]["library"][] = 'cookies_video/default';
    }
  }
}
