<?php

/**
 * @file
 * Contains cookies_instagram.module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cookies_instagram_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cookies_ga module.
    case 'help.page.cookies_instagram':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Submodule of COOKiES to manage Instagram media items (by "Media Entity Instagram" module) in COOKiES consent management.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function cookies_instagram_page_attachments(&$page) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if (!$is_admin) {
    $page["#attached"]["library"][] = 'cookies_instagram/default';
  }
}

/**
 * Implements hook_js_alter().
 *
 * Remove Twitter JS library. Will be added in js/cookies_instagram.js.
 */
function cookies_instagram_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if (!$is_admin) {
    $module_path = drupal_get_path('module', 'media_entity_instagram');
    $scripts = [
      '//platform.instagram.com/en_US/embeds.js',
      $module_path . '/js/instagram.js',
    ];
    foreach ($scripts as $key => $script) {
      if (isset($javascript[$script])) {
        $javascript[$script]['attributes']['type'] = 'application/json';
        $javascript[$script]['attributes']['id'] = 'cookies_instagram_' . $key;
      }
    }
  }
}
