advertisement.advertisement_entity_type.*:
  type: config_entity
  label: 'Advertisement entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'   
    uuid:
      type: string
