<?php

/**
 * @file
 * Contains cookies_ga.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function cookies_ga_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cookies_ga module.
    case 'help.page.cookies_ga':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Submodule of cookies to manage Google Analytics implemented by so named module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function cookies_ga_page_attachments(&$page) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if (!$is_admin && isset($page["#attached"]["html_head"])) {
    foreach ($page["#attached"]["html_head"] as $key => $head_tag) {
      $scripts = ['google_analytics_tracking_script', 'google_analytics_tracking_file'];
      foreach ($scripts as $script) {
        if (in_array($script, $head_tag)) {
          $attr = (isset($head_tag[0]['#attributes'])) ? $head_tag[0]['#attributes'] : [];
          $attr = array_merge($attr, ['type' => 'application/json', 'id' => "cookies_{$script}"]);
          $page["#attached"]["html_head"][$key][0]['#attributes'] = new Attribute($attr);
          $page["#attached"]["library"][] = 'cookies_ga/analytics';
          break;
        }
      }
    }
  }
}
